/// \file devboard.h I/O Definitions for VS10x3 Developer Board

#ifndef DEVBOARD_H
#define DEVBOARD_H

#define EE_GPIO_PIN_CS 0
#define SPI_PIN_SCLK 1 /*SCLK to EEPROM and SD*/

#define SD_GPIO_PIN_CS 3
#define I2C_GPIO_PIN_SDA 4
#define GPIO_PIN_USB_ACTIVITY 4
#define LCD_GPIO_PIN_CS 5
#define I2C_GPIO_PIN_SCL 6
#define LCD_GPIO_PIN_A0 7
#define LCD_GPIO_PIN_RS LCD_GPIO_PIN_A0
#define GPIO_PIN_USB_DETECT 9
#define GPIO_PIN_SDCARD_OFF 8

#define LCD_SET_COMMAND_MODE() USEX(GPIO_ODATA) &= ~(1 << LCD_GPIO_PIN_A0);
#define LCD_SET_DATA_MODE() USEX(GPIO_ODATA) |= (1 << LCD_GPIO_PIN_A0);

#define IO_END_FRAME() USEX(GPIO_ODATA) |= (1 << LCD_GPIO_PIN_CS) | (1 << EE_GPIO_PIN_CS) | (1 << SD_GPIO_PIN_CS);
#define LCD_START_FRAME() {IO_END_FRAME(); USEX(GPIO_ODATA) &= ~(1 << LCD_GPIO_PIN_CS);}
#define SD_START_FRAME() {IO_END_FRAME(); USEX(GPIO_ODATA) &= ~(1 << SD_GPIO_PIN_CS);}
#define EE_START_FRAME() {IO_END_FRAME(); USEX(GPIO_ODATA) &= ~(1 << EE_GPIO_PIN_CS);}
#define SPIRAM_START_FRAME() {IO_END_FRAME(); USEX(GPIO_ODATA) &= ~((1 << EE_GPIO_PIN_CS) | (1 << LCD_GPIO_PIN_CS));}
#define LCD_END_FRAME IO_END_FRAME
#define SD_END_FRAME IO_END_FRAME
#define EE_END_FRAME IO_END_FRAME
#define SPIRAM_END_FRAME IO_END_FRAME

#endif